insert into public.site_content_items (
  title,
  slug,
  section,
  content_type,
  label,
  summary,
  description,
  href,
  image_url,
  image_public_id,
  icon,
  tags,
  metadata,
  status,
  sort_order,
  featured
) values
('Inicio', 'inicio', 'menu', 'nav_link', null, null, null, '#hero', null, null, null, array[]::text[], '{"anchor":"#hero","desktopOnly":false}'::jsonb, 'published', 0, false),
('Competências', 'competencias', 'menu', 'nav_link', null, null, null, '#showcase', null, null, null, array[]::text[], '{"anchor":"#showcase","desktopOnly":false}'::jsonb, 'published', 1, false),
('Projetos', 'projetos', 'menu', 'nav_link', null, null, null, '#projects', null, null, null, array[]::text[], '{"anchor":"#projects","desktopOnly":false}'::jsonb, 'published', 2, false),
('Experiencia', 'experiencia', 'menu', 'nav_link', null, null, null, '#experiences', null, null, null, array[]::text[], '{"anchor":"#experiences","desktopOnly":false}'::jsonb, 'published', 3, false),
('Contato', 'contato', 'menu', 'nav_link', null, null, null, '#network', null, null, null, array[]::text[], '{"anchor":"#network","desktopOnly":false}'::jsonb, 'published', 4, false),
('Texto superior do menu', 'texto-superior-do-menu', 'menu', 'nav_link', 'Portfólio profissional de Paulo Vieira: experiência, competências e cases', null, null, null, null, null, null, array[]::text[], '{"type":"topbar"}'::jsonb, 'published', 100, false),
('Currículo interativo', 'curriculo-interativo', 'hero', 'highlight', null, null, null, null, null, null, null, array[]::text[], '{"group":"highlights","value":"Currículo interativo"}'::jsonb, 'published', 0, false),
('Experiência em e-commerce', 'experiencia-em-e-commerce', 'hero', 'highlight', null, null, null, null, null, null, null, array[]::text[], '{"group":"highlights","value":"Experiência em e-commerce"}'::jsonb, 'published', 1, false),
('Stack full stack', 'stack-full-stack', 'hero', 'highlight', null, null, null, null, null, null, null, array[]::text[], '{"group":"highlights","value":"Stack full stack"}'::jsonb, 'published', 2, false),
('Indicador 6+', 'indicador-6', 'hero', 'stat', 'competências-chave', null, null, null, null, null, null, array[]::text[], '{"group":"stats","value":"6+","label":"competências-chave"}'::jsonb, 'published', 20, false),
('Indicador 3', 'indicador-3', 'hero', 'stat', 'cases selecionados', null, null, null, null, null, null, array[]::text[], '{"group":"stats","value":"3","label":"cases selecionados"}'::jsonb, 'published', 21, false),
('Indicador 100%', 'indicador-100', 'hero', 'stat', 'contato direto', null, null, null, null, null, null, array[]::text[], '{"group":"stats","value":"100%","label":"contato direto"}'::jsonb, 'published', 22, false),
('Selecione competências relevantes', 'selecione-competencias-relevantes', 'hero', 'step', null, null, null, null, null, null, null, array[]::text[], '{"group":"steps","value":"Selecione competências relevantes"}'::jsonb, 'published', 40, false),
('Revise os tópicos de interesse', 'revise-os-topicos-de-interesse', 'hero', 'step', null, null, null, null, null, null, null, array[]::text[], '{"group":"steps","value":"Revise os tópicos de interesse"}'::jsonb, 'published', 41, false),
('Envie a pauta pelo WhatsApp', 'envie-a-pauta-pelo-whatsapp', 'hero', 'step', null, null, null, null, null, null, null, array[]::text[], '{"group":"steps","value":"Envie a pauta pelo WhatsApp"}'::jsonb, 'published', 42, false),
('Front-end', 'front-end', 'showcase', 'competency', null, 'React · Next.js · TypeScript', null, null, null, null, 'frontend', array['React', 'Next.js', 'TypeScript']::text[], '{"cartId":"1","techs":"React · Next.js · TypeScript","filter":"Front-end","available":true,"icon":"frontend"}'::jsonb, 'published', 0, true),
('Back-end', 'back-end', 'showcase', 'competency', null, 'Node.js · Express · APIs REST', null, null, null, null, 'backend', array['Node.js', 'Express', 'APIs REST']::text[], '{"cartId":"2","techs":"Node.js · Express · APIs REST","filter":"Back-end","available":true,"icon":"backend"}'::jsonb, 'published', 1, true),
('E-commerce VTEX', 'e-commerce-vtex', 'showcase', 'competency', null, 'VTEX IO · Fast Store · Shopify', null, null, null, null, 'ecommerce', array['VTEX IO', 'Fast Store', 'Shopify']::text[], '{"cartId":"3","techs":"VTEX IO · Fast Store · Shopify","filter":"E-commerce","available":true,"icon":"ecommerce"}'::jsonb, 'published', 2, true),
('Banco de Dados', 'banco-de-dados', 'showcase', 'competency', null, 'MySQL · Supabase · SQLite', null, null, null, null, 'database', array['MySQL', 'Supabase', 'SQLite']::text[], '{"cartId":"4","techs":"MySQL · Supabase · SQLite","filter":"Dados","available":true,"icon":"database"}'::jsonb, 'published', 3, true),
('DevOps & Deploy', 'devops-deploy', 'showcase', 'competency', null, 'Docker · Vercel · Git CI/CD', null, null, null, null, 'devops', array['Docker', 'Vercel', 'Git CI/CD']::text[], '{"cartId":"5","techs":"Docker · Vercel · Git CI/CD","filter":"Deploy","available":true,"icon":"devops"}'::jsonb, 'published', 4, true),
('Contrato CLT', 'contrato-clt', 'showcase', 'competency', null, 'Propostas de emprego CLT', null, null, null, null, 'clticontrato', array['Propostas de emprego CLT']::text[], '{"cartId":"6","techs":"Propostas de emprego CLT","filter":"Todos","available":false,"icon":"clticontrato"}'::jsonb, 'published', 5, false),
('Front-end', 'front-end', 'skills', 'skill_group', null, null, 'Desenvolvimento de interfaces modernas e responsivas utilizando as melhores práticas de usabilidade e performance.', null, null, null, null, array['JavaScript', 'TypeScript', 'React', 'Next.js']::text[], '{"stacks":[{"name":"JavaScript","icon":"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg"},{"name":"TypeScript","icon":"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg"},{"name":"React","icon":"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg"},{"name":"Next.js","icon":"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg"}]}'::jsonb, 'published', 0, false),
('Back-end', 'back-end', 'skills', 'skill_group', null, null, 'Construção de APIs, integrações com serviços externos, controle de autenticação e organização por camadas.', null, null, null, null, array['Node.js', 'Express']::text[], '{"stacks":[{"name":"Node.js","icon":"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg"},{"name":"Express","icon":"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg"}]}'::jsonb, 'published', 1, false),
('Banco de Dados', 'banco-de-dados', 'skills', 'skill_group', null, null, 'Modelagem simples e objetiva, priorizando consistência e performance.', null, null, null, null, array['MySQL', 'Supabase', 'SQLite']::text[], '{"stacks":[{"name":"MySQL","icon":"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg"},{"name":"Supabase","icon":"/assets/supabase-logo-icon.png"},{"name":"SQLite","icon":"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sqlite/sqlite-original.svg"}]}'::jsonb, 'published', 2, false),
('DevOps & Infraestrutura', 'devops-infraestrutura', 'skills', 'skill_group', null, null, 'Containerização de aplicações, versionamento estruturado e deploy contínuo.', null, null, null, null, array['Docker', 'Vercel', 'Git']::text[], '{"stacks":[{"name":"Docker","icon":"/assets/docker-mark-blue.png"},{"name":"Vercel","icon":"/assets/vercel-icon-light.png"},{"name":"Git","icon":"/assets/github.png"}]}'::jsonb, 'published', 3, false),
('E-commerce', 'e-commerce', 'skills', 'skill_group', null, null, 'Customizações de checkout, componentes e integrações específicas para ambiente VTEX.', null, null, null, null, array['Shopify', 'VTEX']::text[], '{"stacks":[{"name":"Shopify","icon":"/assets/shopify_glyph.png"},{"name":"VTEX","icon":"/assets/vtex-icon.jpg"}]}'::jsonb, 'published', 4, false),
('Bruna Stone & Design', 'bruna-stone-design', 'projects', 'project_card', null, null, 'Landing page responsiva para campanhas de marketing, com foco em apresentação visual, performance e SEO.', 'https://brunastonedesign.com.br/', 'https://res.cloudinary.com/dfddi3cl7/image/upload/v1772820575/Captura_de_tela_2026-03-06_150738_u0fv5t.png', null, null, array['ReactJS', 'Vite', 'Vercel']::text[], '{"badge":"Landing page","stacks":["ReactJS","Vite","Vercel"]}'::jsonb, 'published', 0, true),
('Issacar Church - Album', 'issacar-church-album', 'projects', 'project_card', null, null, 'Galeria para organizar registros visuais da comunidade, com experiência simples para consulta em mobile e desktop.', 'https://github.com/PauloIletski/image-gallery-next-ph', 'https://res.cloudinary.com/dfddi3cl7/image/upload/v1770754208/Captura_de_tela_2026-02-10_170220_cibrkx.png', null, null, array['NextJS', 'Cloudinary API', 'Google API', 'Vercel']::text[], '{"badge":"Aplicação web","stacks":["NextJS","Cloudinary API","Google API","Vercel"]}'::jsonb, 'published', 1, true),
('Cross Ambiental - Novo Site', 'cross-ambiental-novo-site', 'projects', 'project_card', null, null, 'Site institucional modernizado para comunicar soluções com clareza, identidade visual consistente e boa navegação.', 'https://cross-ambiental-landing.vercel.app/', 'https://res.cloudinary.com/dfddi3cl7/image/upload/v1770754902/Captura_de_tela_2026-02-10_172108_gnse6a.png', null, null, array['NextJS', 'Vercel']::text[], '{"badge":"Institucional","stacks":["NextJS","Vercel"]}'::jsonb, 'published', 2, true),
('WPP Commerce', 'wpp-commerce', 'experiences', 'experience_card', null, null, null, 'https://wppcommerce.com.br/', 'https://d335luupugsy2.cloudfront.net/cms/files/90499/1770222188/$doub3fwxayw', null, null, array['Desenvolvedor Full Stack E-commerce e VTEX']::text[], '{"companyLink":"https://wppcommerce.com.br/","role":"Desenvolvedor Full Stack E-commerce e VTEX","duration":"Mar 2020 - Atual","points":["Frontends headless para e-commerce com VTEX Fast Store, VTEX IO, React, Next.js e Gatsby.","Arquitetura frontend, componentes reutilizáveis e otimização de Core Web Vitals.","Atuação em produção, code reviews, decisões técnicas e integração com squads multidisciplinares."],"whiteLogo":true}'::jsonb, 'published', 0, true),
('Quality Digital', 'quality-digital', 'experiences', 'experience_card', null, null, null, 'https://qualitydigital.global/', 'https://qualitydigital.global/wp-content/uploads/2023/04/logo-quality-digital.svg', null, null, array['Desenvolvedor Full Stack E-commerce e VTEX']::text[], '{"companyLink":"https://qualitydigital.global/","role":"Desenvolvedor Full Stack E-commerce e VTEX","duration":"Fev 2026 - Atual","points":["Desenvolvimento de interfaces e integrações para operação digital em escala.","Evolução de componentes, performance e manutenção de jornadas críticas.","Colaboração com times de produto, marketing, QA e operação."],"whiteLogo":false}'::jsonb, 'published', 1, false),
('Minerva Foods', 'minerva-foods', 'experiences', 'experience_card', null, null, null, 'https://minervafoods.com/', 'https://minervafoods.com/wp-content/uploads/2024/08/logo.webp', null, null, array['Service Desk Assistant | Sistemas Internos']::text[], '{"companyLink":"https://minervafoods.com/","role":"Service Desk Assistant | Sistemas Internos","duration":"Jul 2019 - Jan 2020","points":["Suporte e resolução de incidentes em sistemas internos.","Consultas e correções em SQL Server e MySQL.","Gestão de chamados e comunicação com usuários dentro dos SLAs."],"whiteLogo":false}'::jsonb, 'published', 2, false),
('LinkedIn', 'linkedin', 'network', 'social_link', 'Contato profissional', null, null, 'https://www.linkedin.com/in/pauloiletski/', null, null, '/assets/linkedin.png', array[]::text[], '{"label":"Contato profissional","floating":false}'::jsonb, 'published', 0, false),
('GitHub', 'github', 'network', 'social_link', 'Código e projetos', null, null, 'https://github.com/PauloIletski/', null, null, '/assets/github.png', array[]::text[], '{"label":"Código e projetos","floating":false}'::jsonb, 'published', 1, false),
('Linkedin', 'linkedin', 'floatingButtons', 'social_link', null, null, null, 'https://www.linkedin.com/in/pauloiletski/', null, null, '/assets/linkedin.png', array[]::text[], '{"label":"Atalho flutuante","floating":true}'::jsonb, 'published', 0, false),
('Github', 'github', 'floatingButtons', 'social_link', null, null, null, 'https://github.com/PauloIletski/', null, null, '/assets/github.png', array[]::text[], '{"label":"Atalho flutuante","floating":true}'::jsonb, 'published', 1, false),
('Whatsapp', 'whatsapp', 'floatingButtons', 'social_link', null, null, null, 'https://wa.me/5517981048717/?text=Ol%C3%A1+Paulo+sou+[seu+nome]+e+gostaria+de+...', null, null, '/assets/whatsapp.png', array[]::text[], '{"label":"Atalho flutuante","floating":true}'::jsonb, 'published', 2, false),
('Competências', 'competencias', 'footer', 'footer_link', null, null, null, '#showcase', null, null, null, array[]::text[], '{"group":"Currículo"}'::jsonb, 'published', 0, false),
('Cases', 'cases', 'footer', 'footer_link', null, null, null, '#projects', null, null, null, array[]::text[], '{"group":"Currículo"}'::jsonb, 'published', 1, false),
('Experiência', 'experiencia', 'footer', 'footer_link', null, null, null, '#experiences', null, null, null, array[]::text[], '{"group":"Currículo"}'::jsonb, 'published', 2, false),
('LinkedIn', 'linkedin', 'footer', 'footer_link', null, null, null, 'https://www.linkedin.com/in/pauloiletski/', null, null, null, array[]::text[], '{"group":"Canais"}'::jsonb, 'published', 3, false),
('GitHub', 'github', 'footer', 'footer_link', null, null, null, 'https://github.com/PauloIletski/', null, null, null, array[]::text[], '{"group":"Canais"}'::jsonb, 'published', 4, false),
('WhatsApp', 'whatsapp', 'footer', 'footer_link', null, null, null, 'https://wa.me/5517981048717/', null, null, null, array[]::text[], '{"group":"Canais"}'::jsonb, 'published', 5, false)
on conflict (section, slug) do update set
  title = excluded.title,
  content_type = excluded.content_type,
  label = excluded.label,
  summary = excluded.summary,
  description = excluded.description,
  href = excluded.href,
  image_url = excluded.image_url,
  image_public_id = excluded.image_public_id,
  icon = excluded.icon,
  tags = excluded.tags,
  metadata = excluded.metadata,
  status = excluded.status,
  sort_order = excluded.sort_order,
  featured = excluded.featured,
  updated_at = now();
